// <auto-generated />
using System;
using HouseRules.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HouseRules.Migrations
{
    [DbContext(typeof(HouseRulesDbContext))]
    [Migration("20240613191709_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HouseRules.Models.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChoreFrequencyDays")
                        .HasColumnType("integer");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Chore");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChoreFrequencyDays = 1,
                            Difficulty = 1,
                            Name = "Wash Dishes"
                        },
                        new
                        {
                            Id = 2,
                            ChoreFrequencyDays = 7,
                            Difficulty = 2,
                            Name = "Vacuum Living Room"
                        },
                        new
                        {
                            Id = 3,
                            ChoreFrequencyDays = 2,
                            Difficulty = 1,
                            Name = "Take Out Trash"
                        },
                        new
                        {
                            Id = 4,
                            ChoreFrequencyDays = 14,
                            Difficulty = 3,
                            Name = "Clean Bathroom"
                        },
                        new
                        {
                            Id = 5,
                            ChoreFrequencyDays = 7,
                            Difficulty = 4,
                            Name = "Mow Lawn"
                        },
                        new
                        {
                            Id = 6,
                            ChoreFrequencyDays = 3,
                            Difficulty = 2,
                            Name = "Do Laundry"
                        },
                        new
                        {
                            Id = 7,
                            ChoreFrequencyDays = 1,
                            Difficulty = 2,
                            Name = "Cook Dinner"
                        },
                        new
                        {
                            Id = 8,
                            ChoreFrequencyDays = 12,
                            Difficulty = 5,
                            Name = "Clean Windows"
                        },
                        new
                        {
                            Id = 9,
                            ChoreFrequencyDays = 7,
                            Difficulty = 1,
                            Name = "Dust Furniture"
                        },
                        new
                        {
                            Id = 10,
                            ChoreFrequencyDays = 14,
                            Difficulty = 2,
                            Name = "Sweep Garage"
                        },
                        new
                        {
                            Id = 11,
                            ChoreFrequencyDays = 3,
                            Difficulty = 1,
                            Name = "Water Plants"
                        },
                        new
                        {
                            Id = 12,
                            ChoreFrequencyDays = 14,
                            Difficulty = 5,
                            Name = "Organize Pantry"
                        });
                });

            modelBuilder.Entity("HouseRules.Models.ChoreAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChoreId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ChoreAssignment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChoreId = 1,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChoreId = 2,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 3,
                            ChoreId = 3,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 4,
                            ChoreId = 4,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 5,
                            ChoreId = 5,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 6,
                            ChoreId = 6,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 7,
                            ChoreId = 7,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 8,
                            ChoreId = 8,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 9,
                            ChoreId = 9,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 10,
                            ChoreId = 10,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 11,
                            ChoreId = 11,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 12,
                            ChoreId = 12,
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("HouseRules.Models.ChoreCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChoreId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CompletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ChoreCompletion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChoreId = 1,
                            CompletedOn = new DateTime(2024, 6, 12, 14, 17, 8, 746, DateTimeKind.Local).AddTicks(6800),
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChoreId = 2,
                            CompletedOn = new DateTime(2024, 6, 11, 14, 17, 8, 746, DateTimeKind.Local).AddTicks(6890),
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 3,
                            ChoreId = 3,
                            CompletedOn = new DateTime(2024, 6, 10, 14, 17, 8, 746, DateTimeKind.Local).AddTicks(6900),
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 4,
                            ChoreId = 4,
                            CompletedOn = new DateTime(2024, 6, 9, 14, 17, 8, 746, DateTimeKind.Local).AddTicks(6910),
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 5,
                            ChoreId = 5,
                            CompletedOn = new DateTime(2024, 6, 8, 14, 17, 8, 746, DateTimeKind.Local).AddTicks(6920),
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 6,
                            ChoreId = 6,
                            CompletedOn = new DateTime(2024, 6, 7, 14, 17, 8, 746, DateTimeKind.Local).AddTicks(6920),
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 7,
                            ChoreId = 7,
                            CompletedOn = new DateTime(2024, 6, 6, 14, 17, 8, 746, DateTimeKind.Local).AddTicks(6930),
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 8,
                            ChoreId = 8,
                            CompletedOn = new DateTime(2024, 6, 5, 14, 17, 8, 746, DateTimeKind.Local).AddTicks(6930),
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 9,
                            ChoreId = 9,
                            CompletedOn = new DateTime(2024, 6, 4, 14, 17, 8, 746, DateTimeKind.Local).AddTicks(6930),
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 10,
                            ChoreId = 10,
                            CompletedOn = new DateTime(2024, 6, 3, 14, 17, 8, 746, DateTimeKind.Local).AddTicks(6940),
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 11,
                            ChoreId = 11,
                            CompletedOn = new DateTime(2024, 6, 2, 14, 17, 8, 746, DateTimeKind.Local).AddTicks(6950),
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 12,
                            ChoreId = 12,
                            CompletedOn = new DateTime(2024, 6, 1, 14, 17, 8, 746, DateTimeKind.Local).AddTicks(6950),
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("HouseRules.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "101 Main Street",
                            Email = "charlie@kelly.com",
                            FirstName = "Charlie",
                            IdentityUserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            LastName = "Kelly",
                            UserName = "Charlie"
                        },
                        new
                        {
                            Id = 2,
                            Address = "222 Broadway Ave.",
                            Email = "frank@reynolds.com",
                            FirstName = "Frank",
                            IdentityUserId = "frt98wr5-0223-3ww7-t6rq-028g4r521d4e",
                            LastName = "Reynolds",
                            UserName = "Frank"
                        },
                        new
                        {
                            Id = 3,
                            Address = "333 Broadway Ave.",
                            Email = "mac@mcdonald.com",
                            FirstName = "Mac",
                            IdentityUserId = "hdp65oa9-3053-5ap0-z0hh-235t2a098h8q",
                            LastName = "McDonald",
                            UserName = "Mac"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35",
                            Name = "Admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "80806b6a-b9d4-434d-98bc-cfbb6ad6244b",
                            Email = "charlie@kelly.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKM3IEnoaOIeyo8tfwuMEC0tYkOhNDcjMirelQqvH4p0HJbPhBiTexTIRnZJzD4G5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7d8be9d6-7653-48dc-9492-114eae55fd31",
                            TwoFactorEnabled = false,
                            UserName = "Charlie"
                        },
                        new
                        {
                            Id = "frt98wr5-0223-3ww7-t6rq-028g4r521d4e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4bdff836-dab5-4072-8d2f-d69b4f24a9ef",
                            Email = "frank@reynolds.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKQo6XpngyFI5atTS0Ou7125LvRqGVCAR9bJvTks8hy53cBvoUYdxAHmJ+3/sU3nXg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c34f5625-0797-43e7-ad08-abccee5b1b63",
                            TwoFactorEnabled = false,
                            UserName = "Frank"
                        },
                        new
                        {
                            Id = "hdp65oa9-3053-5ap0-z0hh-235t2a098h8q",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "87263e70-21a7-4ed5-965c-64a562553b0e",
                            Email = "mac@mcdonald.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEDKflJsRSZpe9cDJ852ufL1RyqON6ZzRCdSyv+YS0uWW/gtb7A78ZR5OKBSIXwy0Zw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "827a73e7-76a5-435d-875f-a028d54b4ea2",
                            TwoFactorEnabled = false,
                            UserName = "Mac"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HouseRules.Models.ChoreAssignment", b =>
                {
                    b.HasOne("HouseRules.Models.Chore", "Chore")
                        .WithMany("ChoreAssignments")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseRules.Models.UserProfile", "UserProfile")
                        .WithMany("ChoreAssignments")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HouseRules.Models.ChoreCompletion", b =>
                {
                    b.HasOne("HouseRules.Models.Chore", "Chore")
                        .WithMany("ChoreCompletions")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseRules.Models.UserProfile", "UserProfile")
                        .WithMany("ChoreCompletions")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HouseRules.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HouseRules.Models.Chore", b =>
                {
                    b.Navigation("ChoreAssignments");

                    b.Navigation("ChoreCompletions");
                });

            modelBuilder.Entity("HouseRules.Models.UserProfile", b =>
                {
                    b.Navigation("ChoreAssignments");

                    b.Navigation("ChoreCompletions");
                });
#pragma warning restore 612, 618
        }
    }
}
